---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include default variables
  include_vars: "../vars/main.yml"
  tags: bitbucket

- name: include release specific variables
  include_vars: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
  ignore_errors: true
  tags: bitbucket

- name: include release specific tasks
  include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  ignore_errors: true
  tags: bitbucket

# Find User in Passwd Database
- name: "Find Bitbucket Owner in passwd database"
  getent:
    database: passwd
    key: "{{ bitbucket_owner }}"
    fail_key: false

# Find Group in Group Database
- name: "Find Bitbucket Owner group in groups database"
  getent:
    database: group
    key: "{{ bitbucket_group }}"
    fail_key: false

- name: "Define commons facts for roles"
  set_fact:
    bitbucket_owner_exists: "{{ getent_passwd[bitbucket_owner] != None }}"
    bitbucket_group_exists: "{{ getent_group[bitbucket_group] != None }}"
    _bitbucket_create_home: "{{ '--create-home' if bitbucket_create_home else '' }}"
    _bitbucket_owner_system: "{{ '--system' if bitbucket_owner_system else '' }}"

- name: groupadd
  group:
    name: "{{ bitbucket_group }}"
    system: true
    state: present
  tags: bitbucket
  when:
    - not bitbucket_group_exists|bool

- name: useradd
  shell:
  args:
    cmd: "useradd {{ bitbucket_owner }} --home {{ bitbucket_home }} --shell {{ bitbucket_shell }} \
     -g {{ bitbucket_group }} {{ _bitbucket_owner_system }} {{ _bitbucket_create_home }}"
  tags:
    - bitbucket
    - molecule-idempotence-notest
  when:
    - not bitbucket_owner_exists|bool

- name: prepare directories
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: "{{ item.state | default('directory') }}"
  loop:
    - { dest: "/etc/init.d" }
    - { dest: "/lib/systemd/system" }
    - { dest: "{{ bitbucket_download.dest | dirname }}" }
    - { dest: "{{ mysql_jdbc_download.dest | dirname }}" }
    - { dest: "{{ postgresql_jdbc_download.dest | dirname }}" }
    - dest: "{{ bitbucket_catalina }}"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
    - dest: "{{ bitbucket_catalina }}/bin"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
    - dest: "{{ bitbucket_home }}"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
  tags: bitbucket

- name: download archive
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
    timeout: 300
  loop:
    - "{{ bitbucket_download }}"
    - "{{ mysql_jdbc_download }}"
    - "{{ postgresql_jdbc_download }}"
  register: get_url_result
  until: get_url_result is succeeded
  tags: bitbucket

- name: unarchive package
  shell: |
    set -o pipefail
    rm -rf {{ bitbucket_catalina }} \
      && mkdir -p {{ bitbucket_catalina }}
    cd {{ bitbucket_catalina }}
    TMP_DIR="`mktemp -d`" \
      && tar -zx -C $TMP_DIR -f {{ bitbucket_download.dest }} \
      && cp -rfT $TMP_DIR/* . \
      && rm -rf $TMP_DIR
    cd {{ bitbucket_catalina }}/app/WEB-INF/lib
    rm -rf *mysql*.jar
    TMP_DIR="`mktemp -d`" \
      && tar -zx -C $TMP_DIR -f {{ mysql_jdbc_download.dest }} \
      && mv $TMP_DIR/*/*mysql*-bin.jar . \
      && rm -rf $TMP_DIR
    cd {{ bitbucket_catalina }}/app/WEB-INF/lib
    rm -rf *postgresql*.jar
    cp {{ postgresql_jdbc_download.dest }} .
    chown -Rf {{ bitbucket_owner }}:{{ bitbucket_group }} {{ bitbucket_catalina }}
    chmod 0755 \
      {{ bitbucket_catalina }} \
      {{ bitbucket_catalina }}/bin
  args:
    executable: "/bin/bash"
  when: get_url_result is changed
  notify:
    - bitbucket | systemctl daemon-reload
    - bitbucket | systemctl restart
  tags: bitbucket

- name: copy templates
  template:
    dest: "{{ item.dest }}"
    src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - { dest: "/etc/init.d/bitbucket", mode: "0755" }
    - { dest: "/lib/systemd/system/bitbucket.service" }
    - dest: "{{ bitbucket_catalina }}/bin/_start-webapp.sh"
      src: "./templates/opt/atlassian/bitbucket/bin/_start-webapp.sh.j2"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/set-bitbucket-home.sh"
      src: "./templates/opt/atlassian/bitbucket/bin/set-bitbucket-home.sh.j2"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/set-bitbucket-user.sh"
      src: "./templates/opt/atlassian/bitbucket/bin/set-bitbucket-user.sh.j2"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/set-jre-home.sh"
      src: "./templates/opt/atlassian/bitbucket/bin/set-jre-home.sh.j2"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/start-bitbucket.sh"
      src: "./templates/opt/atlassian/bitbucket/bin/start-bitbucket.sh.j2"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/stop-bitbucket.sh"
      src: "./templates/opt/atlassian/bitbucket/bin/stop-bitbucket.sh.j2"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
  notify:
    - bitbucket | systemctl daemon-reload
    - bitbucket | systemctl restart
  tags: bitbucket

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: "{{ item.state | default('file') }}"
  loop:
    - { dest: "/etc/init.d/bitbucket", mode: "0755" }
    - { dest: "/lib/systemd/system/bitbucket.service" }
    - dest: "{{ bitbucket_catalina }}/bin/_start-webapp.sh"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/set-bitbucket-home.sh"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/set-bitbucket-user.sh"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/set-jre-home.sh"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/start-bitbucket.sh"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
    - dest: "{{ bitbucket_catalina }}/bin/stop-bitbucket.sh"
      owner: "{{ bitbucket_owner }}"
      group: "{{ bitbucket_group }}"
      mode: "0755"
  tags: bitbucket

# Ensure that shared directory exists
- name: Ensure that shared directory exists
  file:
    path: "{{ bitbucket_home }}/shared"
    owner: "{{ bitbucket_owner }}"
    group: "{{ bitbucket_group }}"
    mode: "0755"
    state: directory
  tags:
    - molecule-idempotence-notest
  when:
    - bitbucket_properties_file_generation is defined
    - bitbucket_properties_file_generation|bool

# Ensure that property file dont exists
- name: Ensure that property file dont exists
  file:
    path: "{{ bitbucket_home }}/shared/{{ bitbucket_properties_file_name }}"
    state: absent
  tags:
    - molecule-idempotence-notest
  when:
    - bitbucket_properties_file_generation is defined
    - bitbucket_properties_file_generation|bool

- name: Generate bitbucket propertie file with initial content ({{ bitbucket_properties_file_name }})
  blockinfile:
    path: "{{ bitbucket_home }}/shared/{{ bitbucket_properties_file_name }}"
    create: true
    block: |
      server.context-path={{ bitbucket_catalina_context_path }}
      server.port={{ bitbucket_catalina_connector_port }}
      server.secure={{ bitbucket_catalina_connector_secure | lower }}
      server.scheme={{ bitbucket_catalina_connector_scheme }}
    owner: "{{ bitbucket_owner }}"
    group: "{{ bitbucket_group }}"
    mode: "0755"
    state: present
  tags:
    - molecule-idempotence-notest
  when:
    - bitbucket_properties_file_generation is defined
    - bitbucket_properties_file_generation|bool

# Add other properties if exists
- name: Add other properties if exists
  lineinfile:
    dest: "{{ bitbucket_home }}/shared/{{ bitbucket_properties_file_name }}"
    regexp: "^{{ item.key }}=.*$"
    insertafter: "server.scheme"
    line: "{{ item.key }}={{ item.value }}"
    owner: "{{ bitbucket_owner }}"
    group: "{{ bitbucket_group }}"
    mode: "0755"
    state: present
  loop: "{{ bitbucket_extra_properties }}"
  tags:
    - molecule-idempotence-notest
  when:
    - bitbucket_properties_file_generation is defined
    - bitbucket_properties_file_generation|bool
    - bitbucket_extra_properties | length > 0

# Add Proxy properties
- name: Add Proxy name property if exists
  lineinfile:
    dest: "{{ bitbucket_home }}/shared/{{ bitbucket_properties_file_name }}"
    regexp: ".*proxy-name=.*$"
    insertafter: "server.scheme"
    line: "server.proxy-name={{ bitbucket_catalina_connector_proxyname }}"
    owner: "{{ bitbucket_owner }}"
    group: "{{ bitbucket_group }}"
    mode: "0755"
    state: present
  tags:
    - molecule-idempotence-notest
  when:
    - bitbucket_properties_file_generation is defined
    - bitbucket_properties_file_generation|bool
    - bitbucket_catalina_connector_proxyname is defined
    - bitbucket_catalina_connector_proxyname | length > 0

# Add Proxy port properties
- name: Add Proxy port property if exists
  lineinfile:
    dest: "{{ bitbucket_home }}/shared/{{ bitbucket_properties_file_name }}"
    regexp: ".*proxy-port=.*$"
    insertafter: "server.scheme"
    line: "server.proxy-port={{ bitbucket_catalina_connector_proxyport }}"
    owner: "{{ bitbucket_owner }}"
    group: "{{ bitbucket_group }}"
    mode: "0755"
    state: present
  tags:
    - molecule-idempotence-notest
  when:
    - bitbucket_properties_file_generation is defined
    - bitbucket_properties_file_generation|bool
    - bitbucket_catalina_connector_proxyport is defined

- name: flush handlers
  meta: flush_handlers
  tags: bitbucket

- name: enable service
  service:
    name: "bitbucket"
    state: "started"
    enabled: true
  changed_when: false
  ignore_errors: true
  tags: bitbucket
